component: express # (必选) 组件名称，在该实例中为 express
name: translate-api # (必选) 组件实例名称
org: appid # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid，必须为字符串
app: translate-api # (可选) 用于记录组织信息，默认与 name 相同，必须为字符串
stage: dev  # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    src: ./src # 第一种为 string 时，会打包 src 对应目录下的代码上传到默认 cos 上
    exclude: # 被排除的文件或目录
      - .env
  region: ap-beijing # 云函数所在区域
  runtime: Nodejs10.15 # 运行环境
  functionConf: # 函数配置相关
    role: QCS_SCFExcuteRole
    timeout: 5 # 超时时间，单位秒
    memorySize: 256 # 内存大小，单位 MB
    environment: # 环境变量
      variables: # 环境变量数组
        TENCENT_SECRET_ID: ${env:TENCENT_SECRET_ID}
        TENCENT_SECRET_KEY: ${env:TENCENT_SECRET_KEY}
  apigatewayConf: # API 网关配置
    protocols: # 绑定自定义域名的协议类型，默认与服务的前端协议一致
      - http
      - https
    environment: release # 发布环境，目前支持三种发布环境: test（测试）, prepub（预发布） 与 release（发布）
    endpoints:
      - path: /index
        method: ANY